name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Hello World" > test.log 2>&1
        
      - name: 
        uses: actions/upload-artifact@v3
        with:
          path: test.log